[tool.poetry]
name = "mazegen"
version = "0.1.0"
description = "Maze generator"
authors = ["ajeloyan, ajeloyan@student.42lyon.fr & jbordeli, jbordeli@student.42lyon.fr"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "2.12.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"